<?php
/**
 * Theme Option Page
 * @author   Sohrab
 * @since    1.0.0
 * @package  msteele
 * @copyright: style may not be used in any other themes
 */
if ( function_exists( 'acf_add_local_field_group' ) ):

    acf_add_local_field_group( array(
        'key'                   => 'group_msteel_theme_options',
        'title'                 => 'Options',
        'fields'                => array(
            /**
             * Header Tab
             */
            array(
                'key'               => 'msteel_theme_header_tab',
                'label'             => '<div class="settings-icon icon-header"></div> Header',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'left',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_header_logo',
                'label'             => 'Header Logo',
                'name'              => 'header_logo',
                'type'              => 'image',
                'instructions'      => 'Custom header logo',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'url',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_header_image',
                'label'             => 'Header Image',
                'name'              => 'header_image',
                'type'              => 'image',
                'instructions'      => 'Header image',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'url',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_header_logo_link',
                'label'             => 'Header Logo Link',
                'name'              => 'header_logo_link',
                'type'              => 'url',
                'instructions'      => 'Custom logo link, by default the website address is used for the link',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),

            array(
                'key'               => 'field_header_description',
                'label'             => 'Description',
                'name'              => 'header_description',
                'type'              => 'textarea',
                'instructions'      => 'Header Description',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'maxlength'         => '',
                'rows'              => '14',
                'new_lines'         => 'wpautop',
            ),


            /**
             * Footer Tab
             */
            array(
                'key'               => 'msteel_theme_footer_tab',
                'label'             => '<div class="settings-icon icon-footer"></div> Footer',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'left',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_footer_logo_1',
                'label'             => 'Footer Brand Logo',
                'name'              => 'footer_logo_1',
                'type'              => 'image',
                'instructions'      => 'footer Brand logo',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'url',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_footer_logo',
                'label'             => 'Footer Logo',
                'name'              => 'footer_logo',
                'type'              => 'image',
                'instructions'      => 'Custom footer logo',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'url',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_footer_image',
                'label'             => 'Footer Image',
                'name'              => 'footer_image',
                'type'              => 'image',
                'instructions'      => 'Custom footer image',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'url',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_footer_logo_link',
                'label'             => 'Footer Logo Link',
                'name'              => 'footer_logo_link',
                'type'              => 'url',
                'instructions'      => 'Custom logo link',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_footer_logo_link_2',
                'label'             => 'Footer Logo Link 2',
                'name'              => 'footer_logo_link_2',
                'type'              => 'url',
                'instructions'      => 'Custom logo link 2',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
            ),
            array(
                'key'               => 'field_footer_disclaimer',
                'label'             => 'Disclaimer',
                'name'              => 'footer_disclaimer',
                'type'              => 'textarea',
                'instructions'      => 'Disclaimer to be shown in the footer',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'maxlength'         => '',
                'rows'              => '15',
                'new_lines'         => 'wpautop',
            ),

            /**
             * Map Tab
             */
            array(
                'key'               => 'msteel_theme_map_tab',
                'label'             => '<div class="settings-icon icon-map"></div> Map',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'left',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_map_marker',
                'label'             => 'Map Marker',
                'name'              => 'map_marker',
                'type'              => 'image',
                'instructions'      => 'Upload a marker for the map',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'return_format'     => 'url',
                'preview_size'      => 'thumbnail',
                'library'           => 'all',
                'min_width'         => '',
                'min_height'        => '',
                'min_size'          => '',
                'max_width'         => '',
                'max_height'        => '',
                'max_size'          => '',
                'mime_types'        => '',
            ),
            array(
                'key'               => 'field_map_latitude',
                'label'             => 'Latitude',
                'name'              => 'map_latitude',
                'type'              => 'text',
                'instructions'      => 'Location Latitude',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_map_longitude',
                'label'             => 'Longitude',
                'name'              => 'map_longitude',
                'type'              => 'text',
                'instructions'      => 'Location Longitude',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_map_description',
                'label'             => 'Map Description',
                'name'              => 'map_description',
                'type'              => 'textarea',
                'instructions'      => 'A description to show up when clicking on the marker',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'maxlength'         => '',
                'rows'              => '5',
                'new_lines'         => 'wpautop',
            ),
            array(
                'key'               => 'field_map_api_key',
                'label'             => 'API Key',
                'name'              => 'map_api_key',
                'type'              => 'text',
                'instructions'      => 'Enter the API key (click <a href="https://developers.google.com/maps/documentation/javascript/get-api-key?refresh=1" target="_blank">here</a> to get API key for Google Maps.
                                        If you use Leaflet, enter Mapbox API key.',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),


            /**
             * Analytics Tab
             */
            array(
                'key'               => 'msteel_theme_analytics_tab',
                'label'             => '<div class="settings-icon icon-analytics"></div> Analytics',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'left',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_head_tracking_code',
                'label'             => 'Head Tracking Codes',
                'name'              => 'head_tracking_codes',
                'type'              => 'textarea',
                'instructions'      => 'Tracking codes in the head (will be added before the closing head tag)',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'maxlength'         => '',
                'rows'              => '',
                'new_lines'         => '',
            ),
            array(
                'key'               => 'field_body_tracking_code',
                'label'             => 'Body Tracking Codes',
                'name'              => 'body_tracking_codes',
                'type'              => 'textarea',
                'instructions'      => 'Tracking codes in the body (will be added before the closing body tag)',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'maxlength'         => '',
                'rows'              => '',
                'new_lines'         => '',
            ),
            array(
                'key'               => 'field_ga_tracking',
                'label'             => 'Google Analytics',
                'name'              => 'google_analytics_track_id',
                'type'              => 'text',
                'instructions'      => 'Tracking ID',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => 'UA-XXXXX-Y',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),
            array(
                'key'               => 'field_utm_tracking',
                'label'             => 'UTM Domain',
                'name'              => 'utm_tracking_domain',
                'type'              => 'text',
                'instructions'      => 'Domain name without a dot or protocols',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => 'example.com',
                'prepend'           => '',
                'append'            => '',
                'maxlength'         => '',
            ),

            /**
             * Social Network Tab
             */
            array(
                'key'               => 'msteel_theme_social_tab',
                'label'             => '<div class="settings-icon icon-social"></div> Social',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'left',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_social_networks',
                'label'             => 'Social Networks',
                'name'              => 'social_media_networks',
                'type'              => 'repeater',
                'instructions'      => 'Add each individual social network, click <a href="http://fontawesome.io/icons/#brand" target="_blank">here</a> for list of icons. Simply enter the social icon name <code>ex: fa-instagram</code> ',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'collapsed'         => '',
                'min'               => 0,
                'max'               => 0,
                'layout'            => 'table',
                'button_label'      => '',
                'sub_fields'        => array(
                    array(
                        'key'               => 'field_social_media_icon',
                        'label'             => 'Icon',
                        'name'              => 'social_media_icon',
                        'type'              => 'text',
                        'instructions'      => 'Enter a font awesome icon name',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                        'prepend'           => '',
                        'append'            => '',
                        'maxlength'         => '',
                    ),
                    array(
                        'key'               => 'field_social_media_url',
                        'label'             => 'URL',
                        'name'              => 'social_media_url',
                        'type'              => 'url',
                        'instructions'      => 'Enter social network address',
                        'required'          => 0,
                        'conditional_logic' => 0,
                        'wrapper'           => array(
                            'width' => '',
                            'class' => '',
                            'id'    => '',
                        ),
                        'default_value'     => '',
                        'placeholder'       => '',
                    ),
                ),
            ),

            array(
                'key'               => 'field_enable_social_sharings',
                'label'             => 'Enable Social Sharing',
                'name'              => 'enable_social_sharing',
                'type'              => 'true_false',
                'instructions'      => 'Display sharing icons in posts',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 0,
                'ui'                => 1,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),


            /**
             * Additional Codes
             */
            array(
                'key'               => 'msteel_theme_additional_codes_tab',
                'label'             => '<div class="settings-icon icon-code"></div> Codes',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'left',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_header_codes',
                'label'             => 'Header Codes',
                'name'              => 'additional_header_codes',
                'type'              => 'textarea',
                'instructions'      => 'Additional header codes added in the header',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'maxlength'         => '',
                'rows'              => '12',
                'new_lines'         => '',
            ),
            array(
                'key'               => 'field_footer_codes',
                'label'             => 'Footer Codes',
                'name'              => 'additional_footer_codes',
                'type'              => 'textarea',
                'instructions'      => 'Additional footer codes added in the footer',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'default_value'     => '',
                'placeholder'       => '',
                'maxlength'         => '',
                'rows'              => '12',
                'new_lines'         => '',
            ),
            array(
                'key'               => 'field_enable_tracking',
                'label'             => 'Enable Tracking',
                'name'              => 'enable_tracking',
                'type'              => 'true_false',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'message'           => '',
                'default_value'     => 0,
                'ui'                => 1,
                'ui_on_text'        => '',
                'ui_off_text'       => '',
            ),

            /**
             * Other Settings
             */
            array(
                'key'               => 'fmsteel_theme_libraries_tab',
                'label'             => '<div class="settings-icon icon-library"></div> Libraries',
                'name'              => '',
                'type'              => 'tab',
                'instructions'      => '',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '',
                    'class' => '',
                    'id'    => '',
                ),
                'placement'         => 'left',
                'endpoint'          => 0,
            ),
            array(
                'key'               => 'field_ms_theme_libraries',
                'label'             => 'Libraries',
                'name'              => 'ms_theme_libraries',
                'type'              => 'checkbox',
                'instructions'      => 'Select the libraries to include (make sure to read the documentation for usage)',
                'required'          => 0,
                'conditional_logic' => 0,
                'wrapper'           => array(
                    'width' => '100',
                    'class' => '',
                    'id'    => '',
                ),
                'choices'           => array(
                    'animate'             => 'Animate',
                    'aos'                 => 'AOS (Animate on Scroll)',
                    'barba'               => 'Barba JS',
                    'fitvids'             => 'FitVids JS (Full Size Video)',
                    'font-awesome'        => 'Font Awesome',
                    'google-map'          => 'Google Map',
                    'map-api'             => 'Google Map API',
                    'headroom'            => 'Headroom (Header on Scroll)',
                    'jquery-lazy'         => 'jQuery Lazy',
                    'jquery-lazy-plugins' => 'jQuery Lazy Plugins',
                    'lity'                => 'Lity (Light Box)',
                    'leaflet'             => 'Leaflet (Map)',
                    'plyr'                => 'Plyr (Video and Audio)',
                    'slick'               => 'Slick Slider',
                    'smooth-scroll'       => 'Smooth Scrolling',
                ),
                'allow_custom'      => 0,
                'save_custom'       => 0,
                'default_value'     => array(),
                'layout'            => 'vertical',
                'toggle'            => 0,
                'return_format'     => 'value',
            ),

        ),
        'location'              => array(
            array(
                array(
                    'param'    => 'options_page',
                    'operator' => '==',
                    'value'    => 'theme-general-settings',
                ),
            ),
        ),
        'menu_order'            => 0,
        'position'              => 'normal',
        'style'                 => 'default',
        'label_placement'       => 'left',
        'instruction_placement' => 'label',
        'hide_on_screen'        => '',
        'active'                => 1,
        'description'           => '',
    ) );

endif;